### ISSUE TITLE
Typo: Trait uk.gov.hmrc.play.microservice.controller.Utf8MineTypes should be Utf8MimeTypes

### ISSUE THREAD

**Issue by thorbenlouw** [hmrc/microservice-bootstrap#2]
The trait Utf8MineTypes defines ${MimeTypes.JSON};charset=utf-8 and its HTML counterpart, but the trait name is misspelled Utf8Mi[n]eTypes instead of Utf8Mi[m]eTypes

**Comment by duncancrawford** [comment]
Please submit a PR
